"""empty message

Revision ID: 17a4ceac45b7
Revises: dd1116bee7a9
Create Date: 2020-08-11 21:32:04.886449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a4ceac45b7'
down_revision = 'dd1116bee7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_past_shows', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'num_upcoming_shows')
    op.drop_column('Venue', 'num_past_shows')
    # ### end Alembic commands ###
